package TopChefRPG.Exception;

public enum ErrorType {
    NO_DATA, WRONG_TYPE_DATA, INCORRECT_DATA, COOK_NOT_INITIALIZED_CORRECTLY, DATA_NOT_INITIALIZED_IN_BDD, NOT_ENOUGH_INGREDIENT,
    NOT_ENOUGH_EXPERIENCE, WRONG_RECIPE_ID, WRONG_LESSON_ID, ALLREADY_OWNED_LECON
}
